#
# APPLICATION CONFIG
#

management:
  endpoints:
    web:
      exposure:
        include: health,info

# enable gz compression
server:
  port: 8888
  compression:
    enabled: true

spring:
  # jpa:
  #   open-in-view: false
  #   show-sql: false
